---

AllCops:
  Exclude:
    - tmp/**/*

  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 2.3

Layout/ExtraSpacing:
  Description: Do not use unnecessary spacing.
  AllowForAlignment: false

Lint/InterpolationCheck:
  Description: Checks for interpolation in a single quoted string.
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Description: Makes sure that Ruby source files have snake_case names.
  Exclude:
    - .simplecov

TrivialAccessors:
  Description: Looks for trivial reader/writer methods, that could have been created with the attr_* family of functions automatically.
  ExactNameMatch: true

Style/ModuleFunction:
  Description: Checks for use of `extend self` or `module_function` in a module.
  EnforcedStyle: extend_self

# https://github.com/bbatsov/rubocop/pull/72
Style/AsciiComments:
  Description: Checks for non-ascii (non-English) characters in comments.
  Enabled: false

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  EnforcedStyle: double_quotes

# Don't see why storing context information in the exception is a bad thing
Style/RaiseArgs:
  Description: Checks the args passed to `fail` and `raise`.
  Enabled: false

EmptyMethod:
  Description: Checks for the formatting of empty method definitions.
  EnforcedStyle: expanded
