---

AllCops:
  Exclude:
    - tmp/**/*

  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 2.3

Layout/ExtraSpacing:
  AllowForAlignment: false

Lint/InterpolationCheck:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - .simplecov

TrivialAccessors:
  ExactNameMatch: true

Style/ModuleFunction:
  EnforcedStyle: extend_self

# https://github.com/bbatsov/rubocop/pull/72
Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Don't see why storing context information in the exception is a bad thing
Style/RaiseArgs:
  Enabled: false

EmptyMethod:
  EnforcedStyle: expanded
