# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  gem "mdl", "0.13.0"
  gem "rubocop", "~> 1.74"
  gem "rubocop-packaging", github: "utkarsh2102/rubocop-packaging"
  gem "rubocop-performance", "~> 1.24"
  gem "yard", "0.9.37"
end
