# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  gem "mdl", "0.11.0"
  gem "rubocop", "1.28.2"
  gem "rubocop-packaging", "~> 0.5"
  gem "rubocop-performance", "~> 1.3"
  gem "yard", "0.9.26"
end
