---

name: build

on:
  workflow_dispatch:

jobs:
  build:
    name: Ruby ${{ matrix.version.name }} (${{ matrix.line_editor }}, ${{ matrix.compiler }})

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

      matrix:
        version:
          - { name: 3.1, value: 3.1.6 }
          - { name: 3.2, value: 3.2.7 }
          - { name: 3.3, value: 3.3.9 }

        line_editor: [libedit, readline]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.9
          bundler-cache: true

      - name: Build and push docker image
        run: bin/rake docker:build_and_push[${{ matrix.version.value }},${{ matrix.line_editor }},${{ matrix.compiler }}]
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
