---

name: daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_head_images:
    container: deividrodriguez/byebug:2.7.2-readline-gcc

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

      matrix:
        line_editor: [libedit, readline]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v2

      - name: Install Docker client
        run: |
          apk add curl
          curl -L -o /tmp/docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-19.03.5.tgz
          tar -xz --strip-components 1 -C /usr/bin -f /tmp/docker.tgz

      - name: Setup environment
        run: bin/setup.sh

      - name: Build and push docker image
        run: bin/rake docker:build_and_push_head[${{ matrix.line_editor }},${{ matrix.compiler }}]
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        continue-on-error: true

  test_head_images:
    container: deividrodriguez/byebug:head-${{ matrix.line_editor }}-${{ matrix.compiler }}

    needs: build_head_images

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

      matrix:
        line_editor: [libedit, readline]
        compiler: [clang, gcc]

    steps:
      - name: Run CI checks
        run: |
          bin/setup.sh
          bin/rake

    timeout-minutes: 15
