---

name: fedora

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  install_and_run:
    container: fedora:31

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install OS dependencies
        run: dnf install -y ruby ruby-devel make gcc redhat-rpm-config

      - name: Install bundler
        run: gem install bundler:2.2.0.rc.2

      - name: Install development dependencies
        run: bundle install

      - name: Install byebug
        run: bin/rake install

      - name: Run byebug
        run: byebug -h
