---

name: ubuntu

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    name: Ruby ${{ matrix.version.name }} (${{ matrix.line_editor }}, ${{ matrix.compiler }})

    container: deividrodriguez/byebug:${{ matrix.version.value }}-${{ matrix.line_editor }}-${{ matrix.compiler }}

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

      matrix:
        version:
          - { name: 3.1, value: 3.1.6 }
          - { name: 3.2, value: 3.2.9 }
          - { name: 3.3, value: 3.3.9 }

        line_editor: [libedit, readline]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v4

      - name: Run CI checks
        run: |
          bin/setup.sh
          bin/rake

    timeout-minutes: 10
