---

name: ubuntu

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    container: deividrodriguez/byebug:${{ matrix.version }}-${{ matrix.line_editor }}-${{ matrix.compiler }}

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

      matrix:
        version: [3.1.6, 3.2.7, 3.3.7]
        line_editor: [libedit, readline]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v4

      - name: Run CI checks
        run: |
          bin/setup.sh
          bin/rake

    timeout-minutes: 10
