---

name: windows

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  test:
    name: Ruby ${{ matrix.version.name }}

    runs-on: windows-2025

    strategy:
      fail-fast: false

      matrix:
        version:
          - { name: 3.2, value: 3.2.9 }
          - { name: 3.3, value: 3.3.9 }

    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version.value }}

      - name: Setup dependencies
        shell: bash
        run: bin/setup.sh

      - name: Run tests
        run: ruby bin/rake

    timeout-minutes: 10
