---

name: windows

on:
  pull_request:

  push:
    branches:
      - remove-rb-readline-hack-2

jobs:
  test:
    name: Ruby ${{ matrix.version.name }}

    runs-on: windows-2025

    strategy:
      fail-fast: false

      matrix:
        version:
          - { name: 3.3, value: 3.3.9 }

    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version.value }}

      - name: Run tests
        run: |
          ruby foo.rb

    timeout-minutes: 2
