---

name: windows

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    name: Ruby ${{ matrix.version.name }}

    runs-on: windows-2025

    strategy:
      fail-fast: false

      matrix:
        version:
          - { name: 3.1, value: 3.1.6 }
          - { name: 3.2, value: 3.2.7 }
          - { name: 3.3, value: 3.3.9 }

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version.value }}

      - name: Patch rb-readline
        run: |
          git clone -q --depth=5  --no-tags --branch=byebug https://github.com/deivid-rodriguez/rb-readline.git C:\rb-readline
          $n_dir = $(ruby -e "print RbConfig::CONFIG['sitelibdir']")
          Copy-Item -Path C:\rb-readline\lib\* -Destination $n_dir -Recurse

      - name: Setup dependencies
        shell: bash
        run: bin/setup.sh

      - name: Run tests
        run: ruby bin/rake

    timeout-minutes: 10
