---

name: windows

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-2019

    strategy:
      fail-fast: false

      matrix:
        version: [2.5.8, 2.6.6, 2.7.2, head]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: .bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}

      - name: Patch rb-readline
        run: |
          git clone -q --depth=5  --no-tags --branch=byebug https://github.com/deivid-rodriguez/rb-readline.git C:\rb-readline
          $n_dir = $(ruby -e "print RbConfig::CONFIG['sitelibdir']")
          Copy-Item -Path C:\rb-readline\lib\* -Destination $n_dir -Recurse

      - name: Setup dependencies
        shell: bash
        run: bin/setup.sh

      - name: Run tests
        run: ruby bin/rake
        continue-on-error: ${{ matrix.version == 'head' }}

    timeout-minutes: 15
