---

name: windows

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    name: Ruby ${{ matrix.version.name }}

    runs-on: windows-2025

    strategy:
      fail-fast: false

      matrix:
        version:
          - { name: 3.3, value: 3.3.9 }

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version.value }}

      - name: Setup dependencies
        shell: bash
        run: bin/setup.sh

      - name: Run tests
        run: |
          ruby foo.rb
          ruby bin/rake
        env:
          TESTOPTS: --name=test_run_with_a_single_include_flag

    timeout-minutes: 10
