---

name: windows

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-2022

    strategy:
      fail-fast: false

      matrix:
        version: [3.1.6, 3.2.7, 3.3.7]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}

      - name: Patch rb-readline
        run: |
          git clone -q --depth=5  --no-tags --branch=byebug https://github.com/deivid-rodriguez/rb-readline.git C:\rb-readline
          $n_dir = $(ruby -e "print RbConfig::CONFIG['sitelibdir']")
          Copy-Item -Path C:\rb-readline\lib\* -Destination $n_dir -Recurse

      - name: Setup dependencies
        shell: bash
        run: bin/setup.sh

      - name: Run tests
        run: ruby bin/rake

    timeout-minutes: 15
